### ISSUE TITLE
Integrate wrapscan registry into wrapscan UI

### ISSUE THREAD

**Issue by nerfZael** [polywrap/wrapscan-registry#17]

**Comment by pileks** [comment]
Blocked by: https://github.com/polywrap/cli/issues/1846
PR that should resolve this: https://github.com/polywrap/cli/pull/1847

Once this is resolved, we need to redeploy Wraps with a patch version bump.

Wraps currently present on wrapscan:

- ethers
- ens
- ipfs-http-client
- uniswap-v3 (currently not deployed to Wrapscan)
- safe-account-abstraction (currently not deployed to Wrapscan)
- safe-factory
- safe-manager

**Comment by pileks** [comment]
PRs for wraps:

- ethers: https://github.com/polywrap/ethers/pull/95
- ens: pending
- ipfs-http-client: pending
- uniswap-v3: pending
- safe-account-abstraction: pending
- safe-factory: pending
- safe-manager: pending

[] Once all are merged, we can deploy a new version of Wrapscan.

**Comment by pileks** [comment]
Resolved with https://github.com/polywrap/wrapscan-ui/pull/22
