### ISSUE TITLE
Use wrapscan URIs in Rust plugins

### ISSUE THREAD

**Issue by nerfZael** [polywrap/wrapscan-registry#24]
Add "N/A" where not applicable

- [x] File System 
- [x] HTTP
- [x] Ethereum Wallet
- [x] DateTime
- N/A Logging
- N/A Concurrent

**Comment by nerfZael** [comment]
Issue being worked on here: https://github.com/polywrap/wrapscan-registry/issues/24

**Comment by cbrzn** [comment]
once https://github.com/polywrap/datetime/pull/6 is merged we should be good to go!
