### ISSUE TITLE
Use wrapscan URIs in Python plugins

### ISSUE THREAD

**Issue by nerfZael** [polywrap/wrapscan-registry#25]
Add "N/A" where not applicable

- [x] File System 
- [x] HTTP
- [ ] DateTime- N/A
- [x] Ethereum Wallet
- [ ] DateTime - N/A
- [ ] Logging - N/A
- [ ] Concurrent - N/A

**Comment by Niraj-Kamdar** [comment]
You can treat N/A as plugin Not Available here
