### ISSUE TITLE
Specify what wrapscan registry URIs looks like

### ISSUE THREAD

**Issue by nerfZael** [polywrap/wrapscan-registry#4]

**Comment by dOrgJelli** [comment]
Some initial thoughts:
* To give the simplest developer experience as possible, when using Polywrap CLI & Client, we should accept simple `name@version` package URIs.
* `name` can ofc be replaced by `user:package`
* I would recommend disallowing `/` within these shortened registry URIs, as we use that as the "URI authority" delimiter.

Some valid URIs we should accept:
```
# Registry URIs
user:package@1.2.3

# External URIs
## Inferrable
https://github.com/user/package/branch/...
file://...
ipfs/...
## Explicit
wrap://authority/path
wrap://https/...
wrap://ipfs/...
```

**Comment by nerfZael** [comment]
While I do think a simple developer experience is necessary, I don't think we should be breaking the URI format so easily (especially since it's already highly flexible and expressive). 
Additionally, this makes our parsing of URIs even more complex and situational, (if else if...) and might confuse users (since it's hard to figure out the format).

I would prefer something that fits into our current URI scheme:
e.g. `wrapscan/user:package@1.2.3`
